version: '3.9'

services:
  db:
    image: docker-from-zero-to-mastery-dotnet-8-db
    command: mysqld --default_authentication_plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: docker_from_zero_to_mastery_dotnet
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - erudio-network

  docker-from-zero-to-mastery-dotnet-8:
    image: docker-from-zero-to-mastery-dotnet-8
    build:
      context: .
      dockerfile: DockerFromZeroToMastery-ASP.NET-8/Dockerfile
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MySQLConnection__MySQLConnectionString: "Server=db;Port=3308;DataBase=docker_from_zero_to_mastery_dotnet;Uid=docker;Pwd=docker"
    ports:
      - 4430:8080
      - 44300:8081
    depends_on:
      - db
    networks:
      - erudio-network
networks:
  erudio-network:
    driver: bridge
