name: Continuous Integration with GitHub, GitHub Actions and Docker Hub

on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v3

     - name: Log in to Docker Hub
       uses: docker/login-action@v3.0.0
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}

     - name: Build Images
       working-directory: ./02-AfterDockerization/DockerFromZeroToMastery-ASP.NET-8
       run: docker-compose build

     - name: Push to Docker Hub Container Registry
       run: |
         docker tag docker-from-zero-to-mastery-dotnet-8:latest ${{ secrets.DOCKER_USERNAME }}/docker-from-zero-to-mastery-dotnet:latest
         docker tag docker-from-zero-to-mastery-dotnet-8:latest ${{ secrets.DOCKER_USERNAME }}/docker-from-zero-to-mastery-dotnet:${{ github.run_id }}docker tag docker-from-zero-to-mastery-dotnet-8:latest ${{ secrets.DOCKER_USERNAME }}/docker-from-zero-to-mastery-dotnet:latest
         docker tag docker-from-zero-to-mastery-dotnet-8-db:latest ${{ secrets.DOCKER_USERNAME }}/docker-from-zero-to-mastery-dotnet-8-db:latest
         docker tag docker-from-zero-to-mastery-dotnet-8-db:latest ${{ secrets.DOCKER_USERNAME }}/docker-from-zero-to-mastery-dotnet-8-db:${{ github.run_id }}
         
         docker push ${{ secrets.DOCKER_USERNAME }}/docker-from-zero-to-mastery-dotnet:latest
         docker push ${{ secrets.DOCKER_USERNAME }}/docker-from-zero-to-mastery-dotnet:${{ github.run_id }}
         docker push ${{ secrets.DOCKER_USERNAME }}/docker-from-zero-to-mastery-dotnet-8-db:latest
         docker push ${{ secrets.DOCKER_USERNAME }}/docker-from-zero-to-mastery-dotnet-8-db:${{ github.run_id }}